# Generated by Django 5.2.4 on 2025-07-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.AddField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="demand_level",
            field=models.CharField(
                choices=[("High", "High"), ("Normal", "Normal"), ("Low", "Low")],
                default="Normal",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
