# Generated by Django 5.2.4 on 2025-07-17 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_product_in_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Store Manager", max_length=100)),
                ("store_address", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("contact", models.CharField(blank=True, max_length=20)),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="Include country code (e.g., +1234567890)",
                        max_length=20,
                    ),
                ),
                ("low_stock_threshold", models.IntegerField(default=10)),
                ("whatsapp_alerts_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Manager Profile",
                "verbose_name_plural": "Manager Profiles",
            },
        ),
        migrations.CreateModel(
            name="LowStockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("threshold_value", models.IntegerField()),
                ("stock_at_alert", models.IntegerField()),
                ("manager_phone", models.CharField(max_length=20)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Low Stock Alert",
                "verbose_name_plural": "Low Stock Alerts",
                "ordering": ["-sent_at"],
            },
        ),
    ]
