# Generated by Django 4.2.7 on 2025-08-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_managerprofile_lowstockalert"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="selling_price",
        ),
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="profit_margin",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="product",
            name="profit_per_unit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
